[package]
name = "py_executer"
version = "0.1.2"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
clap = { version = "4.5.37", features = ["derive"] }
colored = "3.0.0"
anyhow = "1.0.98"

[lib]
name = "py_executer_lib"
path = "src/lib/py_executer_lib.rs"